# Generated by Django 6.0.4 on 2026-04-21 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Digimon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Digimon Name', max_length=100)),
                ('digi_type', models.CharField(choices=[('Data', 'Data'), ('Vaccine', 'Vaccine'), ('Virus', 'Virus'), ('Unknown', 'Unknown'), ('None', 'None')], max_length=20)),
                ('element', models.CharField(choices=[('Fire', 'Fire'), ('Water', 'Water'), ('Ice', 'Ice'), ('Earth', 'Earth'), ('Wind', 'Wind'), ('Thunder', 'Thunder'), ('Steel', 'Steel'), ('Dark', 'Dark'), ('Light', 'Light')], max_length=20)),
                ('stage', models.CharField(choices=[('Rookie', 'Rookie'), ('Rookie X', 'Rookie X'), ('Champion', 'Champion'), ('Champion X', 'Champion X'), ('Ultimate', 'Ultimate'), ('Ultimate X', 'Ultimate X'), ('Mega', 'Mega'), ('Mega X', 'Mega X'), ('Burst Mode', 'Burst Mode'), ('Burst Mode X', 'Burst Mode X'), ('Jogress', 'Jogress'), ('Jogress X', 'Jogress X'), ('Hybrid', 'Hybrid'), ('Variant', 'Variant'), ('Armor', 'Armor')], max_length=30)),
                ('size', models.FloatField(default=140.0, help_text='Boyut yüzdesi (%)')),
                ('hatch_level', models.IntegerField(choices=[(3, '3/5'), (4, '4/5'), (5, '5/5'), (6, '6/5'), (7, '7/5')], default=5, help_text='Hatch aşaması (3/5, 4/5, 5/5)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='digimons/images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digimons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DigimonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=0, help_text='Health Points')),
                ('ds', models.IntegerField(default=0, help_text='Digisoul')),
                ('at', models.IntegerField(default=0, help_text='Attack')),
                ('as_speed', models.FloatField(default=0.0, help_text='Attack Speed')),
                ('ct', models.FloatField(default=0.0, help_text='Critical Hit (%)')),
                ('cd', models.FloatField(default=0.0, help_text='Critical Damage (%)')),
                ('ht', models.IntegerField(default=0, help_text='Hit Rate')),
                ('de', models.IntegerField(default=0, help_text='Defense')),
                ('bl', models.FloatField(default=0.0, help_text='Block (%)')),
                ('ev', models.FloatField(default=0.0, help_text='Evasion (%)')),
                ('sk', models.FloatField(default=0.0, help_text='Skill Damage (%)')),
                ('digimon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='digimon.digimon')),
            ],
        ),
        migrations.CreateModel(
            name='DigimonEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_digimon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_evolutions', to='digimon.digimon')),
                ('to_digimon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_evolutions', to='digimon.digimon')),
            ],
            options={
                'unique_together': {('from_digimon', 'to_digimon')},
            },
        ),
    ]
