# Generated by Django 6.0.4 on 2026-04-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digimon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digimon',
            name='element',
            field=models.CharField(choices=[('Fire', 'Fire'), ('Light', 'Light'), ('Steel', 'Steel'), ('Wind', 'Wind'), ('Ice', 'Ice'), ('Neutral', 'Neutral'), ('Thunder', 'Thunder'), ('Wood', 'Wood'), ('Land', 'Land'), ('Dark', 'Dark'), ('Water', 'Water')], max_length=20),
        ),
    ]
